name: encdec_Cond
use_mask: ${use_mask_encoder}
condition: true
decoder:
  layer_name: EncDecoder
  d_model: ${embed_dim}
  n_heads: 8
  n_enc_layers: 3
  n_dec_layers: 3
  n_landmarks: ${num_joints}
  transformer_dim_feedforward: 2048
  ldmks_dim: 2
  dropout: 0.1
  uncertainty: true